# Week 2--The basics of Python


- Module 2 covers python basics
    - Notes (Current page)
    - Youtube video

## I.1 Running Python

### I.1.1 Anaconda
- Anaconda downloads python and jupyter notebook (you are currently viewing a jupyter notebook)
- [Link](https://www.anaconda.com/products/individual)

### I.1.2 UV (for advanced users)
- UV downloads python and allows for version control
- [Link](v/getting-started/installation/)

### I.1.3 Binder (for beginners)
- Use binder by clicking on the binder button on our course homepage: https://mybinder.org/v2/gh/Data-Science-Public-Policy/graspp_2025_spring/HEAD

<img src="Screenshots/binder.png" />

# 2. Where is this notebook? Where is my Data? 


### IMPORTANT: If you are running on google colab you need to drag the csv file into your workspace
###

## 2.1 `File path`: fancy way to say the current folder you are working from

### 2.1.A Current folder

In [1]:
# Current path
import os
# os.getcwd(): Shows current folder this notebook is in
os.getcwd()

'/Users/cory/Desktop/datascience-publicpolicy-2026/notebooks/week_2'

In [5]:
# This shows the files in the folder two folders above the current folder
os.listdir("../..")

['requirements.txt',
 'uv.lock',
 'environment.yml',
 'pyproject.toml',
 'README.md',
 '.gitignore',
 '.venv',
 '.git',
 'data',
 'notebooks',
 'src']

In [10]:
# This shows the files in the data/examples folder
os.listdir("../../data/examples/week_2")

['world_bank_data.csv']

### 2.1.1 Saving data: In this case words (a.k.a. a string)

In [21]:
# In python if you write a name (without spaces) and you write something on the right hand side this saves data/information
file_location = "../../data/examples/week_2/"
file_location

'../../data/examples/week_2/'

In [ ]:
# This line saves the web address (URL) of the World Bank data file as text in a variable named 'url'.
url = "https://raw.githubusercontent.com/corybaird/datascience-publicpolicy-2026/refs/heads/main/data/examples/week_2/world_bank_data.csv"

In [ ]:
# This line prints the url
url

## 2.2 Importing data (csv, excel, stata) to the notebook

In [22]:
os.listdir(file_location)

['world_bank_data.csv']

### 2.2.1 Import

In [23]:
import pandas as pd
pd.read_csv("../../data/examples/week_2/world_bank_data.csv")

,Unnamed: 0,indicator,country,countryiso3code,date,value
0,0,GDP per capita (current US$),Canada,CAN,2023,53431.185706
1,1,GDP per capita (current US$),Canada,CAN,2022,55509.393176
2,2,GDP per capita (current US$),Canada,CAN,2021,52496.844169
3,3,GDP per capita (current US$),Japan,JPN,2023,33766.526825
4,4,GDP per capita (current US$),Japan,JPN,2022,34017.271808
5,5,GDP per capita (current US$),Japan,JPN,2021,40058.537328
6,6,GDP per capita (current US$),Mexico,MEX,2023,13790.024343
7,7,GDP per capita (current US$),Mexico,MEX,2022,11385.407076
8,8,GDP per capita (current US$),Mexico,MEX,2021,10314.050674
9,9,GDP per capita (current US$),United States,USA,2023,82769.412211
10,10,GDP per capita (current US$),United States,USA,2022,78035.175360
11,11,GDP per capita (current US$),United States,USA,2021,71318.307359

### 2.2.2 Import and save to notebook (same concept as 1.1.1)

In [25]:
df = pd.read_csv(file_location + "world_bank_data.csv")

,Unnamed: 0,indicator,country,countryiso3code,date,value
0,0,GDP per capita (current US$),Canada,CAN,2023,53431.185706
1,1,GDP per capita (current US$),Canada,CAN,2022,55509.393176
2,2,GDP per capita (current US$),Canada,CAN,2021,52496.844169
3,3,GDP per capita (current US$),Japan,JPN,2023,33766.526825
4,4,GDP per capita (current US$),Japan,JPN,2022,34017.271808
5,5,GDP per capita (current US$),Japan,JPN,2021,40058.537328
6,6,GDP per capita (current US$),Mexico,MEX,2023,13790.024343
7,7,GDP per capita (current US$),Mexico,MEX,2022,11385.407076
8,8,GDP per capita (current US$),Mexico,MEX,2021,10314.050674
9,9,GDP per capita (current US$),United States,USA,2023,82769.412211
10,10,GDP per capita (current US$),United States,USA,2022,78035.175360
11,11,GDP per capita (current US$),United States,USA,2021,71318.307359

### 2.2.3 Exploring the Data
Now that the data is loaded, let's take a peek at it. We can look at the top (`head`), the bottom (`tail`), and get a summary (`info`).

In [ ]:
df.head(2)

In [ ]:
df.tail(2)

In [ ]:
df.info()