# Reading Web Data
This notebook focuses on importing data from the web (APIs, URLs).

# 1. Importing Data
- All data and code for this course including this notebook is viewable on our course page below
    - https://github.com/Data-Science-Public-Policy/graspp_2025_spring/tree/main

## 1.1. Review: Importing local data

In [ ]:
import pandas as pd
pd.read_csv("../../data/examples/week_2/world_bank_data.csv")

## 1.2 Importing data from github

### 1.2.1 Importing the data

In [3]:
# This line saves the web address (URL) of the World Bank data file as text in a variable named 'url'.
url = "https://raw.githubusercontent.com/corybaird/datascience-publicpolicy-2026/refs/heads/main/data/examples/week_2/world_bank_data.csv"

# This line uses the pandas library's 'read_csv' function.
# A DataFrame is essentially a Python version of an Excel spreadsheet, a two-dimensional table with rows and columns.
import pandas as pd
df = pd.read_csv(url)

# The 'head(2)' returns the first 2 rows of the DataFrame.
df.head(2)

,Unnamed: 0,indicator,country,countryiso3code,date,value
0,0,GDP per capita (current US$),Canada,CAN,2023,53431.185706
1,1,GDP per capita (current US$),Canada,CAN,2022,55509.393176

In [8]:
# This line does the exact same thing as the previous line, but it directly uses the URL string, instead of the variable 'url'.
# It reads the World Bank data from the given URL and stores it as a pandas DataFrame named 'df'.
df = pd.read_csv("https://raw.githubusercontent.com/corybaird/datascience-publicpolicy-2026/refs/heads/main/data/examples/week_2/world_bank_data.csv")

# The 'head(3)' returns the first 3 rows of the DataFrame.
df.head(3)

,Unnamed: 0,indicator,country,countryiso3code,date,value
0,0,GDP per capita (current US$),Canada,CAN,2023,53431.185706
1,1,GDP per capita (current US$),Canada,CAN,2022,55509.393176
2,2,GDP per capita (current US$),Canada,CAN,2021,52496.844169

## 1.3 Importing data via an API

### 1.3.A Introducing functions

In [9]:
# We already used functions!

# function to read csvs from the pandas library
# pd.read_csv()
# function to read html from the pandas library
# pd.read_html()

#### 1.3.A.1 Basic function

In [10]:
# Now we make our own
def num_print(a):
    return a

In [11]:
num_print(8)

8

In [12]:
num_print(7)

7

#### 1.3.A.2 Multiple arguments

In [13]:
def add_func(a,b,c):
    print('This function adds')
    final = a+b+c
    return final

In [14]:
add_func(10,20,10)

This function adds

40

### 1.3.1 Function to download data from the world bank WDI

### Just trust me for now!
Don't worry if the code block below looks like an alien language. We are defining a custom function to grab web data. Just execute the cell to see the data, and we will break down exactly how variables and data types work in the next notebook.

In [21]:
import requests
import pandas as pd
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    # Use io.BytesIO to pass the bytes content as a file-like object to read_xml
    df = pd.read_xml(io.BytesIO(response.content))
    return df

In [23]:
# Example 1
data = download_worldbank(
    indicator = 'NY.GDP.PCAP.CD' , 
    countries = ['US', 'CA', 'MX', 'JP'],  
    date_start = '2021', 
    date_end = '2023'
)
data.head(2)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),Canada,CAN,2023,54220.328504,NaN,NaN,1
1,GDP per capita (current US$),Canada,CAN,2022,56256.800726,NaN,NaN,1

### What is a List? (Just-in-Time Setup)
To tell the API which countries we want, we need to pass it multiple items using a **List**...

#### Lists syntax

- Lists can be made up of strings or numbers
- Spacing is not necessarily important!

In [78]:
import requests
import pandas as pd
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    # Use io.BytesIO to pass the bytes content as a file-like object to read_xml
    df = pd.read_xml(io.BytesIO(response.content))
    return df


# REMEMBER WE USED LISTS BEFORE
# Example 2: Using saved objects
indicator_code = 'SP.POP.TOTL'  # Example: Total population
country_list = ['FR', 'DE', 'IT'] # France, Germany, Italy
start_year = '2020'
end_year = '2022'

data2 = download_worldbank(
    indicator=indicator_code,
    countries=country_list,
    date_start=start_year,
    date_end=end_year
)
data2.head(2)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"Population, total",Germany,DEU,2022,83177813,NaN,NaN,0
1,"Population, total",Germany,DEU,2021,83196078,NaN,NaN,0

In [79]:
my_list = ['Python', 'R', 'Stata', 'Excel']

my_list

['Python', 'R', 'Stata', 'Excel']

In [80]:
my_list = [3, 
           5,
           9,
           11]
type(my_list)

list

In [24]:
# Example 2: Using saved objects
indicator_code = 'SP.POP.TOTL'  # Example: Total population
country_list = ['FR', 'DE', 'IT'] # France, Germany, Italy
start_year = '2020'
end_year = '2022'

data2 = download_worldbank(
    indicator=indicator_code,
    countries=country_list,
    date_start=start_year,
    date_end=end_year
)
data2.head(2)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"Population, total",Germany,DEU,2022,83177813,NaN,NaN,0
1,"Population, total",Germany,DEU,2021,83196078,NaN,NaN,0